// Sprint 1481 — END-TO-END cross-language parity for the pool -> earner rail.
//
// The other suites verify the contract against JS-built trees, and the Python
// suite verifies the builder against EVM-emitted leaf goldens. Neither on its own
// proves the thing that actually matters in production:
//
//     a Merkle proof built by PYTHON is accepted by the EVM, and pays out.
//
// If the two implementations ever diverge (leaf encoding, double-hash, sorted-pair
// order, odd-node promotion, address casing, entry sort), an epoch would publish
// fine and then every claim would revert InvalidProof — funds reserved on chain and
// unclaimable, with nothing failing loudly at build time.
//
// The fixture is generated by prsm/settlement/reward_epoch.py (regenerate with the
// snippet in that module's test) and consumed here unmodified.
const { expect } = require("chai");
const { ethers, upgrades } = require("hardhat");
const fixture = require("./fixtures/reward_epoch_python.json");

describe("OperatorRewardPool — Python-built proof parity", function () {
  let ftns, pool, owner, publisher, treasury;

  beforeEach(async function () {
    const signers = await ethers.getSigners();
    owner = signers[0];
    publisher = signers[1];
    treasury = signers[9];

    const Token = await ethers.getContractFactory("FTNSTokenSimple");
    ftns = await upgrades.deployProxy(
      Token, [owner.address, treasury.address],
      { initializer: "initialize", kind: "uups" }
    );
    await ftns.waitForDeployment();

    const Pool = await ethers.getContractFactory("OperatorRewardPool");
    pool = await Pool.deploy(
      await ftns.getAddress(), owner.address, publisher.address
    );
    await pool.waitForDeployment();
  });

  it("★ the EVM accepts every proof built by the Python builder, and pays exactly", async function () {
    const total = BigInt(fixture.total_amount_wei);
    await ftns.connect(treasury).transfer(await pool.getAddress(), total);

    // The Python-computed root is published verbatim — no JS re-derivation.
    await pool.connect(publisher).publishEpoch(
      fixture.epoch_id, fixture.merkle_root, total
    );

    let paid = 0n;
    for (const e of fixture.entries) {
      const amount = BigInt(e.amount_wei);
      const before = await ftns.balanceOf(e.account);

      // Sanity: the contract agrees the Python leaf is claimable BEFORE we spend gas.
      expect(await pool.isClaimable(fixture.epoch_id, e.account, amount, e.proof))
        .to.equal(true);

      await pool.connect(owner).claim(
        fixture.epoch_id, e.account, amount, e.proof
      );
      expect(await ftns.balanceOf(e.account)).to.equal(before + amount);
      paid += amount;
    }

    // Every wei reserved by the Python-declared total was claimable — no dust
    // stranded, no overdraw.
    expect(paid).to.equal(total);
    expect(await pool.totalReserved()).to.equal(0n);
    expect(await ftns.balanceOf(await pool.getAddress())).to.equal(0n);
  });

  it("★ the Python-computed root equals the root the EVM derives from the same leaves", async function () {
    // Recompute each leaf ON CHAIN from (epochId, account, amount) and fold with
    // the contract's own convention; it must reproduce Python's published root.
    const leaves = [];
    for (const e of fixture.entries) {
      leaves.push(await pool.leafHash(
        fixture.epoch_id, e.account, BigInt(e.amount_wei)
      ));
    }
    const hashPair = (a, b) => {
      const [x, y] = a.toLowerCase() <= b.toLowerCase() ? [a, b] : [b, a];
      return ethers.keccak256(ethers.concat([x, y]));
    };
    let layer = leaves;
    while (layer.length > 1) {
      const next = [];
      for (let i = 0; i < layer.length; i += 2) {
        next.push(i + 1 < layer.length ? hashPair(layer[i], layer[i + 1]) : layer[i]);
      }
      layer = next;
    }
    expect(layer[0]).to.equal(fixture.merkle_root);
  });

  it("★ FULL RAIL: finalized batches -> emission plan -> tree -> published + claimed on chain", async function () {
    // This fixture came from the complete off-chain pipeline:
    //   BatchFinalized records -> build_emission_epoch (pro-rata over settled value,
    //   exactly-once attribution) -> plan_to_reward_epoch (Merkle tree).
    // Publishing and draining it here proves the links compose: the pot is fully
    // distributed, every provider's proof verifies, and nothing is left stranded.
    const railFixture = require("./fixtures/emission_epoch_from_batches.json");
    const pot = BigInt(railFixture.pot_wei);
    expect(BigInt(railFixture.total_amount_wei)).to.equal(pot); // leaves sum to the pot

    await ftns.connect(treasury).transfer(await pool.getAddress(), pot);
    await pool.connect(publisher).publishEpoch(
      railFixture.epoch_id, railFixture.merkle_root, pot
    );

    let paid = 0n;
    for (const e of railFixture.entries) {
      const amount = BigInt(e.amount_wei);
      const before = await ftns.balanceOf(e.account);
      await pool.connect(owner).claim(
        railFixture.epoch_id, e.account, amount, e.proof);
      expect(await ftns.balanceOf(e.account)).to.equal(before + amount);
      paid += amount;
    }
    // The emission pot is distributed to the wei — no dust stranded in the pool,
    // and no earner left unable to claim.
    expect(paid).to.equal(pot);
    expect(await pool.totalReserved()).to.equal(0n);
    expect(await ftns.balanceOf(await pool.getAddress())).to.equal(0n);
  });

  it("a tampered amount from the Python fixture is rejected on chain", async function () {
    const total = BigInt(fixture.total_amount_wei);
    await ftns.connect(treasury).transfer(await pool.getAddress(), total);
    await pool.connect(publisher).publishEpoch(
      fixture.epoch_id, fixture.merkle_root, total
    );
    const e = fixture.entries[0];
    await expect(
      pool.connect(owner).claim(
        fixture.epoch_id, e.account, BigInt(e.amount_wei) + 1n, e.proof)
    ).to.be.revertedWithCustomError(pool, "InvalidProof");
  });
});
